export enum EMESSAGES {
    CHECK = 'CHECK',
    SEND_TO_ALL = 'SEND_TO_ALL',
    GET_LOBBIES = 'GET_LOBBIES',
    DROP_FROM_LOBBY = 'DROP_FROM_LOBBY',
    GAME_STARTED = 'GAME_STARTED',
    GET_CURRENT_LOBBY = 'GET_CURRENT_LOBBY',
    UPDATE_USER_ADDRESS = 'UPDATE_USER_ADDRESS'
};

export const MEDIATOR = {
    EVENTS: {
        REGISTRATION: 'REGISTRATION',
        LOGIN: 'LOGIN',
        LOGOUT: 'LOGOUT',
        SHOW_ERROR: 'SHOW_ERROR',
        PROFILE_BUTTON: 'PROFILE_BUTTON',
        CART_BUTTON: 'CART_BUTTON',
        SET_TO_REGISTRATION: 'SET_TO_REGISTRATION',
        SET_TO_LOGIN: 'SET_TO_LOGIN',
        SET_TO_ACCOUNT: 'SET_TO_ACCOUNT',
        SET_TO_ACCOUNT_INFO: 'SET_TO_ACCOUNT_INFO',
        UPDATE_USER_ADDRESS: 'UPDATE_USER_ADDRESS',
        ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',
        DEL_PRODUCT_FROM_CART: 'DEL_PRODUCT_FROM_CART',
        CLEAR_CART: 'CLEAR_CART',
        UPDATE_CART: 'UPDATE_CART',
        CREATE_ORDER: 'CREATE_ORDER',
        SET_ORDERS: 'SET_ORDERS',
        CANCEL_ORDER: 'CANCEL_ORDER',
        SHOW_ADMIN_PANEL_BUTTON: 'SHOW_ADMIN_PANEL_BUTTON',
        SET_PAIGE_ADMIN_PANEL: 'SET_PAIGE_ADMIN_PANEL'

    },
    TRIGGERS: {
        GET_TOKEN: 'GET_TOKEN',
        GET_GUID: 'GET_GUID',
        GET_USER: 'GET_USER',
        GET_CURRENT_CART: 'GET_CURRENT_CART',
        GET_ORDERS: 'GET_ORDERS'
    }
};

export type TWINDOW = {
    LEFT: number;
    TOP: number;
    HEIGHT: number;
    WIDTH: number;
}

const CONFIG = {
    HOST: 'http://localhost:3001', // Адрес сервера
};

export default CONFIG;